### ISSUE TITLE
WSDL - Server inaccessibility

### ISSUE THREAD

**Issue by Loocos** [Prometee/VIESClient#6]
Hi,

- https://ec.europa.eu/taxation_customs/vies/
- https://ec.europa.eu/taxation_customs/vies/checkVatService.wsdl

These links resume to this page https://sorry.ec.europa.eu/

All the links are down, client are facing error 500 when ordering products. 

```
ViesSoapClient on line 29 
SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://ec.europa.eu/taxation_customs/vies/checkVatService.wsdl' : Namespace prefix xlink for href on use is not defined
```

It could be good to handle this exception with a try/catch and ignore it instead of blocking orders.
What do you think @Prometee ?

Thanks in advance

**Comment by Loocos** [comment]
Service came back

**Comment by Prometee** [comment]
Hello @Loocos,

The web service is not 100% up all time that's why the [`ViesHelper`](https://github.com/Prometee/VIESClient/blob/master/src/Helper/ViesHelper.php) is making a try/catch to catch the `SoapFault`.
Are you able to paste the Stack trace of the error to be able to catch the right `Exception` you had ?

**Comment by Loocos** [comment]
@Prometee arf! I was thinking to capture it but I don't have. The only thing I've is that the exception occur at ViesSoapClient.php on line 29 in the constructor. I think we can get the stack trace by disabling our network or denying the IP of the europa website.

I'll try to get it like that, and see if it produce the same stack trace.

**Comment by Prometee** [comment]
Normally it's covered by this tests here : https://github.com/Prometee/VIESClient/blob/master/tests/Helper/ViesHelperTest.php#L38-L55
It change the WebService URL which make the SOAP call fail and catch, resulting value will be `ViesHelperInterface::CHECK_STATUS_VALID_FORMAT` or `ViesHelperInterface::CHECK_STATUS_INVALID`

**Comment by Prometee** [comment]
@Loocos when using the bundle : https://github.com/Prometee/VIESClientBundle i'm trying to avoid loading the `ViesSoapClient` service using the service attribute `lazy`. This will avoid loading the WSDL when it's not used.
(I think I already tried but I don't remember why I abandoned this idea, will see where it lead us).

```yaml
services:
    
    Prometee\VIESClient\Soap\Client\ViesSoapClient:
        lazy: true
```

**Comment by Prometee** [comment]
Sorry for coming back to you after a too long time.

I was annoyed by this issue happening during several hours last week, and I think I manage to build a way to avoid the constructor to create error when the WSDL is not accessible.
That's why you can now found a class named [`DeferredViesSoapClient`](https://github.com/Prometee/VIESClient/blob/master/src/Soap/Client/DeferredViesSoapClient.php) it basically avoid to construct the `ViesSoapClient` and construct it if there is a call to one of the webservice methods, this way the helper will catch SOAP errors even if the WSDL is not available.

I will update the bundle to use this client by default now.
